services:
  - type: web
    name: unison-core-service
    env: node
    plan: free
    buildCommand: npm install && npx tsc
    startCommand: node --max-old-space-size=400 dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: FORCE_PERMISSIONS_GRANTED
        value: "true"
